### ISSUE TITLE
Add support for nested local spans

### ISSUE THREAD

**Issue by hyleung** [hyleung/ratpack-zipkin#10]
Possibly look at https://github.com/openzipkin/brave/commit/c97129e70168762665ff3ced3cfdd022536b600c for pointers.

**Comment by hyleung** [comment]
@schlosna (cc @adriancole)  Had a look at the commit for`InheritableServerClientAndLocalSpanState` - thought I could model my implementation after it. Had a quick look and one thing that might make it a bit easier  could be to use something like a marker interface here (https://github.com/openzipkin/brave/commit/c97129e70168762665ff3ced3cfdd022536b600c#diff-7be6b1b0b4fbe00b0bdf7b070442c90bR93) instead of checking for an instance of a concrete class. That way, an implementer could implement `ServerClientAndLocalSpanState` and "declare" that they're capable of supporting nested local spans by just adding the marker interface. In my case, while I suppose I could extend `InheritableServerClientAndLocalSpanState`, but `ThreadLocal`s aren't really gonna work with Ratpack.

If that seems reasonable, I'm happy to open and issue/submit a PR to make it happen.

**Comment by codefromthecrypt** [comment]
Mentioned this many times on different pull requests, but not on this
thread.

Inheritable... is a workaround to a design flaw in brave's context
propagation. While clever we really shouldn't add more duct tape on this.

Google agreed to share their purpose-built context, including publishing a
zero dependencies jar as of version 1.0.1

http://www.grpc.io/grpc-java/javadoc/io/grpc/Context.html

Let's just fix the root problem :)

**Comment by hyleung** [comment]
@adriancole ah I see. Sorry to make you repeat yourself again! There's so much going on with Zipkin these days it's hard to keep track of things.

**Comment by codefromthecrypt** [comment]
no worries. I mentioned it here, as I know it gets lost in comments :)

**Comment by hyleung** [comment]
Hmm..ok so I guess grpc `Context` makes `InheritableServerClientAndLocalSpanState` go away then? Would `LocalTracer` then just assume that nested local spans are supported? i.e. this part of `LocalTracer` (https://github.com/openzipkin/brave/blob/master/brave-core/src/main/java/com/github/kristofa/brave/LocalTracer.java#L116) would just check to see if there's a current local span, if so, use that as the parent - otherwise, use the current server span.

**Comment by codefromthecrypt** [comment]
In the future design, all spans are equal.

Ex there is no difference between a server parent and a non server parent.
When you create a new span, it is either a new trace or a child of what was
there before.

When you log an annotation, you log it to whatever the current span is. Say
we do an adapter, LocalTracer, ClientTracer etc would use the same context
underneath.

Make sense?

On 18 Sep 2016 11:38 am, "Ho Yan Leung" notifications@github.com wrote:

Hmm..ok so I guess grpc Context makes InheritableServerClientAndLoca
lSpanState go away then? Would LocalTracer then just assume that nested
local spans are supported? i.e. this part of LocalTracer (
https://github.com/openzipkin/brave/blob/master/
brave-core/src/main/java/com/github/kristofa/brave/LocalTracer.java#L116)
would just check to see if there's a current local span, if so, use that as
the parent - otherwise, use the current server span.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/hyleung/ratpack-zipkin/issues/10#issuecomment-247823152,
or mute the thread

**Comment by codefromthecrypt** [comment]
Would be like duck typing as opposed to using different span objects. I
will copy you on some finagle stuff in the next day or two to help explain.

**Comment by hyleung** [comment]
@adriancole I have no idea how you manage to track all this stuff (tho' it is _greatly_ appreciated). Yeah, it makes sense. If the design is likely to be changing in the near future, I might just wait until the dust settles. Is https://github.com/openzipkin/brave/issues/166 the issue to be following?

**Comment by codefromthecrypt** [comment]
I don't know how I track either :) anyway I am currently finishing up
finagle with brave in mind. Now that it is possible  (grpc released)
probably a couple weeks or so of partial focus, unless someone beats me to
it.

On 18 Sep 2016 1:12 pm, "Ho Yan Leung" notifications@github.com wrote:

@adriancole https://github.com/adriancole I have no idea how you manage
to track all this stuff (tho' it is _greatly_ appreciated). Yeah, it makes
sense. If the design is likely to be changing in the near future, I might
just wait until the dust settles. Is openzipkin/brave#166
https://github.com/openzipkin/brave/issues/166 the issue to be following?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/hyleung/ratpack-zipkin/issues/10#issuecomment-247826067,
or mute the thread

**Comment by drmaas** [comment]
Any updates on this? This would be a useful feature for tracing arbitrarily nested code.

**Comment by hyleung** [comment]
@drmaas Short answer, "no". For the most part this library leverages stuff that Brave supports (implementing adapters, etc. to make it play nice with RatPack) - so probably the first step in re-starting efforts on this would be to dig into where Brave is on this.

**Comment by llinder** [comment]
@hyleung correct me if I'm wrong but with Brave 4 API should allow nested local traces now.  When your running on the same thread it should be easy.  Things get more complicated if you need to propagate context across threads as the API leaves this as an exercise for the user.

For an example this should work fine today:
```Java
Span root = tracer.newTrace().name("root_name").start();
try {
  Span child1 = tracer.newChild(root.context()).name("child1_name").start();
  try {
    doSomethingExpensive();

    Span child2 = tracer.newChild(child1.context()).name("child2_name").start();
    try {
      doSomethingElseExpensive();
    } finally {
      child2.finish();
    }
  } finally {
    child1.finish();
  }

} finally {
  span.finish();
}
```

More information is here:
https://github.com/openzipkin/brave/tree/master/brave#tracing

**Comment by hyleung** [comment]
@llinder haha...i don't think I'm in *any* position to correct *anybody*. Try as I might, Brave has been moving so quickly that it's hard to keep track.

In the snipped above, that's the type of `tracer`?

**Comment by llinder** [comment]
@hyleung I always assume I am wrong to a certain extent :)

The type is `brave.Tracer`.  v4 unified everything so there is only one tracer.  You can create multiple tracers with different names if is desired.  The nice thing is that the new API provides an adapter so you can create a Tracer with v4 and then instantiate an instance of Brave using the TracerAdapter https://github.com/openzipkin/brave/tree/master/brave#upgrading-from-brave-3  This should make it easier to adopt without doing a whole sale rewrite where your already using v3.

**Comment by hyleung** [comment]
@llinder ahh...yeah I think there used to be a `LocalTracer` which might have been the problem. I'm gonna give this a go and see if the spans look ok and maybe then we can think about whether this need any additional support. Thanks!

**Comment by codefromthecrypt** [comment]
great work, folks

**Comment by llinder** [comment]
@hyleung I added a test for this specific case https://github.com/hyleung/ratpack-zipkin/pull/33  I think that covers the feature request.  Let me know if you think we should expand on this further.
