### ISSUE TITLE
Upgrade to brave 4.1.0

### ISSUE THREAD

**Issue by drmaas** [hyleung/ratpack-zipkin#22]
At the minimum, this would involve using the new `brave.Tracer` instead of `LocalTracer`.

**Comment by codefromthecrypt** [comment]
FYI Brave 4.1 will be out shortly and will include a replacement api for in-process propagation https://github.com/openzipkin/brave/pull/369

**Comment by hyleung** [comment]
@adriancole yeah, I saw that this morning - might just skip straight to 4.1. Hoping to have some time to look into upgrading this repo soon (been busy with other stuff lately so haven't been doing the best job keeping up with changes).

**Comment by hyleung** [comment]
Looks like @llinder is already on the upgrade to Brave 4.1 -  https://github.com/hyleung/ratpack-zipkin/pull/24

**Comment by hyleung** [comment]
I've also started (in parallel) a spike exploring a more incremental approach - https://github.com/hyleung/ratpack-zipkin/pull/25

**Comment by hyleung** [comment]
@llinder wanted to get your thoughts about how we should proceed (thought I'd do it here instead of in the PR).

At the moment, I'm thinking of maybe starting off with the more incremental approach - get this library updated to Brave 4.1.0 with as few major changes as necessary - that way we might be able to provide some features to address #10 because then we'll have `Tracer` at our disposal.  Then we can do that major version bump and start breaking shit 😛. 

If the timing works out, https://github.com/openzipkin/brave/pull/350 might be far along enough for us to incorporate. With that, plus your work on #24, we'll be able to drop the dependency on `brave-http` and maybe add support for some of the stuff @adriancole mentioned for 350.

**Comment by llinder** [comment]
Sounds like a plan 👍

There are some nice things in #350 that is worth waiting for when its ready.  Until then it probably makes sense to go with #25 as you suggest.

**Comment by hyleung** [comment]
@llinder looks like I jumped the gun a little - did more testing and realized that I was picking up an old snapshot artifact. So it wasn't actually working properly. It wasn't crashing, but it also wasn't recording any traces. I'd still like to be able to do something incremental but I'm a little less confident that we can pull it off now 😄

**Comment by hyleung** [comment]
@llinder let's keep chipping away at #24 then, given that the incremental approach isn't really working out.

**Comment by hyleung** [comment]
Updated to Brave 4.2 in #24
