### ISSUE TITLE
Pass Context to HttpAdapter instead of Request/Response

### ISSUE THREAD

**Issue by llinder** [hyleung/ratpack-zipkin#39]
There is a desire to access parts of the context to customize annotations in the [HttpParser](https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpParser.java).  Rather than pulling the request and the response off the context to send to [HttpAdapter](https://github.com/hyleung/ratpack-zipkin/blob/master/src/main/java/ratpack/zipkin/internal/DefaultServerTracingHandler.java#L46) we could instead send the Context so its available to the HttpParser.

pseudo code
```
static final class HttpAdapter extends brave.http.HttpServerAdapter<Context, Context> {

    @Override public String method(Context context) {
      return context.getRequest().getMethod().getName();
    }

    @Override public String path(Context context) {
      return context.getRequest().getPath();
    }

    @Override public String url(Context context) {
      return context.getRequest().getUri();
    }

    @Override public String requestHeader(Context context, String name) {
      return context.getRequest().getHeaders().get(name);
    }

    @Override public Integer statusCode(Context context) {
      return context.getResponse().getStatus().getCode();
    }
  }
```

**Comment by codefromthecrypt** [comment]
curious.. which parts?

**Comment by llinder** [comment]
The use case I've seen is folks wanting to access `getPathBinding()` to build up search friendly tags.   Having access to the `PathBinding` object makes it easier to turn something like `/devices/123/components/main` into `/devices/*/components/*` so its easier to perform a trace search on.  PathBinding makes it easier as Ratpack as already processed the token placeholders and its just a matter of reconstructing the URL minus the placeholders.

**Comment by llinder** [comment]
For the record I prefer not using the Context but without it there isn't a clear way to access the PathBinding object.

**Comment by codefromthecrypt** [comment]
So, there's no way to navigate to the PathBinding from the request or
response objects? I think there's a similar dillemma in JAX-RS (to
access the uri template)

**Comment by tylershaosamsung** [comment]
@adriancole we havent found Context from Response object

**Comment by codefromthecrypt** [comment]
Thinking out-loud about options.. One way to do this which seems a bit
more straightforward is to add a special method to a subtype of
HttpServerParser

/** Customizes the span based on the request context */
public <Req> void context(Context context, SpanCustomizer customizer) {
}

Let's say this type is RatpackServerParser.. in the place where the
request is handled, we check instanceof and then call context
accordingly?

**Comment by codefromthecrypt** [comment]
another way is that we could add pathbinding to the registry prior to
calling the handler..

https://ratpack.io/manual/current/api/ratpack/http/Request.html#add-java.lang.Class-O-

**Comment by hyleung** [comment]
Argh, apologies - got busy in the day job so haven't been paying as much attention as I ought to...

If we don't want to pass the entire `Context` (I'm with @llinder on this one), we could create our own class that provides a restricted (probably read-only) API that allows access to the details of the `Request`, `Response`, and `PathBinding`. 

One thing that I came across just now while trying a few things out - I tried logging out the `PathBinding` in the [`handle` method](https://github.com/hyleung/ratpack-zipkin/blob/master/src/main/java/ratpack/zipkin/internal/DefaultServerTracingHandler.java#L32-L44) of the `DefaultServerTracingHandler` and for some reason, there the `PathBinding` seems to be empty at the point where the `HttpServerHandler` is invoked - i.e. if you try to get `ctx.getPathBinding().getDescription()` at that point, you get nothing. Interestingly enough, if you try to log out the `PathBinding` in the `beforeSend`, you get the path binding as expected.

**Comment by llinder** [comment]
@hyleung thanks for your feedback.   I think either a custom response class with some read only methods or adding `public <Req> void context(Context context, SpanCustomizer customizer)` to the `HttpServerParser` are good options.

One advantage of the `context` method on the `HttpServerParser` is that its a bit more flexible at the expense of exposing more details.

From the sounds of it, in order to use the `PathBinding` to create a span name it would require a custom `HttpServerParser` as the base one sets the span name in the `request` method.

https://github.com/openzipkin/brave/blob/master/instrumentation/http/src/main/java/brave/http/HttpParser.java#L19

**Comment by codefromthecrypt** [comment]
PS I'm cool with whatever, just playing devils advocate on the type. Usually I try to find something that's more requesty for the request type, but optimizing for that isn't helpful if it makes it less usable on the whole. appreciate the thoughts

**Comment by hyleung** [comment]
Are there any other use cases that come to mind that would require `Context` to be exposed fully? Unless there are a lot other use cases,  personally my preference would be to err on the side of being conservative about what we expose - we can always  expose _more_ as the use cases become more apparent. 

Implementation aside, I think being able to use the path binding to build up those tags would be pretty sweet just by itself. What do you think about looking at that as the "feature"  - work towards enabling that - _then_ think about how we can make it more general?

**Comment by llinder** [comment]
Nothing else on the `Context` seems immediately useful at first glance.  Just exposing the `PathBinding` for now is fine by me.

**Comment by hyleung** [comment]
@llinder don't suppose you have any idea why `PathBinding` is only present at the very end before the response is sent? Wonder if it's to do with the way the handler chain works...

In any case, I'm up for taking a stab at this but if anybody else wants to champion it, I'm happy to just follow along!

**Comment by hyleung** [comment]
Hey y'all

Sorry for the radio silence. I have to confess I've been sort of procrastinating on this. I have a [WIP branch](https://github.com/hyleung/ratpack-zipkin/tree/add-path-bindings-to-adapter) with something that does work but am still trying to figure out what the API should look like. This is probably verging into bike-shedding territory, but so far I've come up with three different ways to expose this extension point.

In all these cases we will re-work the adapters and server parsers, etc. - that bit is pretty easy.

The question is: as far as public API exposed to consumers of the library go, what's appropriate to expose. Obviously there's kind of a user experience angle to it (i.e. how much yak shaving to we want people to have to do) but there's also (in my mind) the desire to expose as little surface area as possible so that we have more options when it comes to being able to change our minds (e.g. about the implementation). Also having to do casts, etc. is just....icky.

## Option 1

We just use the existing `Config.serverParser(HttpServerParser)` method in the module config and the user can override what they want - but they'll have to cast a few things if they want access to extra information (e.g `PathBinding`).

It would look somethink like this:

```
.module(ServerTracingModule.class, config -> config
                .serviceName("other-server")
                .sampler(Sampler.create(samplingPct))
                .spanReporter(spanReporter())
                .serverParser(new HttpServerParser() {

                  @Override
                  public <Req> void request(final HttpAdapter<Req, ?> adapter, final Req req, final SpanCustomizer customizer) {
                    RatpackServerHttpAdapter ratpackAdapter = (RatpackServerHttpAdapter) adapter;
                    //do some stuff
                    super.request(adapter, req, customizer);
                  }
                }))
```

This option would actually always be available because that `serverParser(HttpServerParser)` method in the config is already there and we probably wouldn't remove it.

## Option 2

We _add_ the ability to configure a provider (probably a `FunctionalInterface`, because it's more Ratpack-y) and *we* take care of all the casts and whatnot. We just apply the provided provider in our ServerParser implementation.

It would look something like this:

```
@FunctionalInterface
public interface RatpackSpanCustomizer {
  void execute(RatpackServerHttpAdapter adapter,
               ServerResponseContext responseContext,
               Throwable error,
               SpanCustomizer customizer);
}
```

```
.module(ServerTracingModule.class, config -> config
                .serviceName("other-server")
                .sampler(Sampler.create(samplingPct))
                .spanReporter(spanReporter())
                .withRatpackSpanCustomizer((adapter, responseContext, error, customizer) ->
                    customizer.tag("pathBinding", responseContext.getPathBinding().getDescription())))
```

This is what I've currently got on my WIP branch.

## Option 3

We don't even expose the custom adapter, but instead just allow the user to configure providers that return just values, like `Iterable<Pair<String, String>>`. In the ServerParser, we do the casting, etc. and iterate through the data that's returned when we invoke the providers. Again, this feels more Ratpack-y (which, personally, I like).

This would look something like this:

```
@FunctionalInterface
public interface TagProvider {
  Iterable<Pair<String, String>> parseTags(ServerRequestContext requestContext, ServerResponseContext responseContext);
}
```

...where `ServerRequestContext` and `ServerResponseContext` are interfaces that provide information about the request and response. We can't use the stock Ratpack types here because things like the `PathBinding` aren't accesible from those types.

The module configuration would be:

```
.module(ServerTracingModule.class, config -> config
    .serviceName("other-server")
    .sampler(Sampler.create(samplingPct))
    .spanReporter(spanReporter())
    .withTagProvider(((requestContext, responseContext) -> 
        Collections.singleton(Pair.of("foo", "bar")
    ))))
```

And, of course, there would be different providers to allow customizations of other aspects of the Span (e.g. Annotations, etc.).

**Comment by codefromthecrypt** [comment]
looks like a sensible set of options. one thing I'd recommend is making
sure that a normal HttpServerParser can be passed without casting (As we'll
likely get configuration bindings to it at some point).

Also, if there are attributes needed that aren't convenient to ask upstream
to move them :P

**Comment by llinder** [comment]
Thanks for writing this up @hyleung !   Option 2 or 3 seem like useful additions.

The original use case that started this request was specifically a way to create generic Span names using the Ratpack PathBinding object.    I think any approach that allows access to the Span.name method with the response context and having it invoked at a point when the PathBinding has been set is fine with me.  It feels like this would be possible with something along the lines of Option 2 where the lambda is invoked during the `Context.beforeSend` method.

**Comment by hyleung** [comment]
@adriancole ~so, it's *supposed* to be possible to pass a normal `HttpServerParser` that doesn't do any casting, etc. That's actually meant to work *right now* - i.e. it's not related to this change. I tested it out and it works ok when you override `HttpServerParser.request`, but `HttpServerParser.response` appears to be a little borked because the types aren't lining up. I probably forgot a `<T>` somewhere along the way.~ 

Scratch that... it does work. User error 🤦‍♂️.  

Good call on checking to see if we can get some of those attributes made available upstream. I haven't kept up to date with Ratpack lately. 

Anyhow - I'm gonna try to get to something workable with option 3.

**Comment by codefromthecrypt** [comment]
Sounds good. In a related note running the stock http client and server
tests will ensure the normal customization works. Not saying it doesnt now.
Not sure how easy it is to roll in here
https://github.com/openzipkin/brave/blob/master/instrumentation/http-tests/src/main/java/brave/http/ITHttpServer.java

**Comment by hyleung** [comment]
@adriancole 👍  thx for the tip. IIRC @llinder did that with `ITHttpClient`. Hopefully we can get it working for the server stuff too.
